dependencies:
  - "OpenZeppelin/openzeppelin-contracts@4.5.0"
  
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
networks:
  development:
    verify: False
  
  rinkeby:
    verify: True

  polygon-test:
    verify: True
  mumbai_moralis:
    verify: True

dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}